version: '3'
services:
  backend:
    build: ./backend
    image: dannyboyjr/clonebnb_backendIMG
    env_file:
      - /root/backend.env
    ports:
      - "8080:8000"
    container_name: backend_clonebnb_container
    restart: always

  frontend:
    build: ./frontend
    image: dannyboyjr/clonebnb_frontendIMG
    env_file:
      - /root/backend.env
    ports:
      - "3000:3000"
    container_name: frontend_clonebnb_container
    restart: always

  
